"""Init

Revision ID: 61fda4afe32d
Revises: 
Create Date: 2025-06-05 12:31:47.386381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fda4afe32d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part_descriptions')
    op.drop_table('service_tickets')
    op.drop_table('service_mechanics')
    op.drop_table('mechanics')
    op.drop_table('customers')
    op.drop_table('serialized_parts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serialized_parts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description_id', sa.INTEGER(), nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['part_descriptions.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=360), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mechanics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=360), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('salary', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('service_mechanics',
    sa.Column('ticket_id', sa.INTEGER(), nullable=False),
    sa.Column('mechanic_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanics.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'mechanic_id')
    )
    op.create_table('service_tickets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('VIN', sa.VARCHAR(length=100), nullable=False),
    sa.Column('service_date', sa.VARCHAR(length=50), nullable=False),
    sa.Column('service_desc', sa.VARCHAR(length=255), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_descriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('part_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=255), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
